# Generated by Django 5.2.1 on 2025-05-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
