# Generated by Django 5.2.1 on 2025-05-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
